---
title: "SCIP_mturk-study1B_analysis"
author: "Pooja Paul"
date: "12/9/2019"
output:
  html_document:
    toc: true
    toc_depth: 2
---

```{r opts, include=FALSE, echo = FALSE, cache = FALSE}
knitr::opts_chunk$set(echo = TRUE)

# edited line below to help with saving plots as .png files; 
# knitr::opts_chunk$set(echo = TRUE, dev = c('png', 'pdf'),fig.align = 'center') 
   

```
# Load packages

```{r loadPackages, echo = FALSE, message=FALSE, warning=FALSE}

library(here)
library(langcog)   #install.packages("devtools"); devtools::install_github("langcog/langcog")
library(Hmisc) # --- could use this for alt. bootstrapping fns

# added 9-27-19 - I
library(stringr) #processing strings
library(compute.es) #for calculating effect sizes
library(lme4) 
#library(regex) 

#added 9-27-19 - II
# install.packages(c("skimr", "visdat", "summarytools", "DT"))
library(skimr)
library(visdat)
# library(summarytools)  # must have XQuartz installed 
# getting following error: package ‘summarytools’ was built under R version 3.5.2 couldn't connect to display ":0"system has no X11 capabilities, therefore only ascii graphs will be produced by dfSummary()
library(DT)
library(tidyverse)  #note: contains ggplot2, dplyr, tidyr
library(car)
library(lme4)

```

# Structure data

Steps in data processing pipeline:

(1) Load csv file containing raw ON/OFF data (Qualtrics 'Hot Spots' Question type) 
    -- Note: no timing info included in this datafile.

```{r tidyUp, echo = FALSE, message=FALSE, warning=FALSE}
files <- dir(here("SCIP_1B_data_ANON"), "*.csv")
d <- tibble(fname = files) %>%
  mutate(id = c(1,10,11,12,2,3,4,9,13,14,15,16,5,6,7,8)) %>% # adds index to keep track of data frames
  arrange(id) %>% # arranges in ascending list order
  select(id, fname) %>% 
  split(.$id) %>% # splits into list of data frames
  map_df(function (x) {  # defines function to run on each data frame
    read_csv(here("SCIP_1B_data_ANON", x$fname)) %>% 
      select(ends_with("_1"), -contains("timing")) %>% 
      mutate(listNum = x$id, 
             subid = str_c(as.character(listNum), '-', as.character(1:n()))) %>%
  pivot_longer(names_to = "trial", 
               values_to = "response", cols = c(-listNum, -subid)) %>%
  separate(trial, sep = "-", into = c("trialName", "jars")) %>% 
  mutate(response = ifelse(response=="On", 
                           "left",ifelse(response=="Off","right","NA"))) %>% 
  mutate(trialType = "critical",
         trialType = ifelse(str_detect(trialName, "G"), "gen", trialType),
         trialType = ifelse(str_detect(trialName, "R"), "recap", trialType)) %>%
  mutate(trialName = str_replace(trialName, ":purple",""),
         jars = str_replace(str_replace(jars, "_1", ""), "white", "PW")) })


    # Still TODO:
      # (d) fix Cr naming issue in lists 9-16
```


Merge in key information and score trials
```{r echo = FALSE, message=FALSE, warning=FALSE}
keys <- read_csv("SCIP_1B_key_full.csv") 

#TODO: missing some Cr 'correctSide' values in later lists --- fix 
d <- left_join(d, keys) %>%
  mutate(acc = ifelse(response==correctSide,1,0))


```

Aggregate and plot. 

```{r fullData}
#grouping by trial type (Critical/Generalization/Recap)
ms <- d %>%   
  group_by(trialType, subid) %>%
  summarise(acc = mean(acc, na.rm=TRUE)) %>%
  multi_boot_standard(col = "acc", na.rm = TRUE)
ggplot(ms, aes(x = trialType, y = mean, fill = trialType)) + 
  geom_bar(stat = "identity") +
  geom_linerange(aes(ymin = ci_lower, ymax = ci_upper)) + 
  geom_hline(yintercept = .5, lty = 3)


#grouping by trial name (n = 8)
ms <- d %>%   
  group_by(trialName, subid) %>%
  summarise(acc = mean(acc, na.rm=TRUE)) %>%
  multi_boot_standard(col = "acc", na.rm = TRUE)
ggplot(ms, aes(x = trialName, y = mean, fill = trialName)) + 
  geom_bar(stat = "identity") +
  geom_linerange(aes(ymin = ci_lower, ymax = ci_upper)) + 
  geom_hline(yintercept = .5, lty = 3)




#TODO: fix labeling issue with 'Cr' trials
#TODO: use faceting to separate into groups by familiarization order 
          # INCREASING = odd numbered lists
          # DECREASING = even numbered lists

```
```{r byFamOrder}
# df with just INCREASING fam order (odd-numbered lists)
ms_increasing <- d %>% 
  filter(listNum %in% c(1,3,5,7,9,11,13,15)) %>% 
  #group_by(trialType, id) %>%
  group_by(trialName, subid) %>%
  summarise(acc = mean(acc, na.rm=TRUE)) %>%
  multi_boot_standard(col = "acc", na.rm = TRUE)
#ggplot(ms_increasing, aes(x = trialType, y = mean, fill = trialType)) + 
ggplot(ms_increasing, aes(x = trialName, y = mean, fill = trialName)) + 
  geom_bar(stat = "identity") +
  geom_linerange(aes(ymin = ci_lower, ymax = ci_upper)) + 
  geom_hline(yintercept = .5, lty = 3)

# df with just DECREASING fam order (even-numbered lists)
ms_decreasing <- d %>% 
  filter(listNum %in% c(2,4,6,8,10,12,14,16)) %>% 
  #group_by(trialType, id) %>%
  group_by(trialName, subid) %>%
  summarise(acc = mean(acc, na.rm=TRUE)) %>%
  multi_boot_standard(col = "acc", na.rm = TRUE)
#ggplot(ms_decreasing, aes(x = trialType, y = mean, fill = trialType)) + 
ggplot(ms_decreasing, aes(x = trialName, y = mean, fill = trialName)) +  
  geom_bar(stat = "identity") +
  geom_linerange(aes(ymin = ci_lower, ymax = ci_upper)) + 
  geom_hline(yintercept = .5, lty = 3)
```
